# FAVICON (avoid console error)
favicon:
  path: /favicon.ico
  controller:
  methods: GET

translationRequests:
  resource: routes/translationRequests.yaml
  prefix: /api/

translationResults:
  resource: routes/translationResults.yaml
  prefix: /api/
