parameters:
  routing.uuid: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Kernel.php'

  App\UI\Controller\:
    resource: "../src/UI/Controller/"
    tags: ["controller.service_arguments"]

  App\UI\Subscriber\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  _instanceof:
    App\Shared\Domain\Bus\Query\QueryHandler:
      tags: [{ name: messenger.message_handler, bus: query.bus }]

    App\Shared\Domain\Bus\Command\CommandHandler:
      tags: [{ name: messenger.message_handler, bus: command.bus }]

    App\Shared\Domain\Bus\Event\EventSubscriber:
      tags: [messenger.message_handler]

    App\Translations\Domain\Contract\TranslationProvider:
      tags: ['app.translation_provider']

  App\Shared\Domain\Bus\Event\EventBus:
    class: App\Shared\Infrastructure\Bus\Event\RabbitMQ\RabbitMQEventBus

  App\Translations\Domain\Service\RequestExternalTranslation:
    arguments:
      $primaryTranslationProvider: '@App\Translations\Infrastructure\Http\DeepL\DeepLTranslationProvider'
      $translationProviders: !tagged_iterator app.translation_provider

  App\Translations\Infrastructure\Http\DeepL\DeepLTranslationProvider:
    arguments:
      $apiKey: "%env(resolve:DEEPL_API_KEY)%"
      $baseUri: "%env(resolve:DEEPL_BASE_URI)%"

  App\Translations\Infrastructure\Http\LectoAI\LectoAITranslationProvider:
    arguments:
      $apiKey: "%env(resolve:LECTOAI_API_KEY)%"
      $baseUri: "%env(resolve:LECTOAI_BASE_URI)%"
