services:
  db:
    image: postgres:alpine
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 6432:5432
    networks:
      - symfony_app

  message_broker:
    image: rabbitmq:management
    volumes:
      - "rabbitmq:/var/lib/rabbitmq:cached"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - symfony_app

  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    networks:
      - symfony_app

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    environment:
      NGINX_BACKEND_DOMAIN: ${NGINX_BACKEND_DOMAIN}
      NGINX_PUBLIC_FOLDER_PATH: ${NGINX_PUBLIC_FOLDER_PATH}
    ports:
      - 8000:80
    networks:
      - symfony_app

volumes:
  symfony_app_var:
  symfony_app_vendor:
  pgdata:
  rabbitmq:

networks:
  symfony_app:
